#!/bin/bash

cd $OPENSHIFT_REPO_DIR

. ".openshift/config.example"

cd $SERVER_DIR

echo "Starting Vert.x application" $OPENSHIFT_REPO_DIR$SERVER_DIR/$SERVER_FILE

if [[ -e $SERVER_FILE ]]; then
	nohup bash -c "exec 'vertx' 'run' '${SERVER_FILE}' &> ${OPENSHIFT_DIY_LOG_DIR}server.log" &> /dev/null &
	echo $! > application.pid
else
	echo "Server file does not exists."
fi
